### ISSUE TITLE
GraphViz not working

### ISSUE THREAD

**Issue by abolt** [rapidprom/rapidprom-source#19]
Exception: java.lang.RuntimeException
Message: Graphviz-dot binary not found. 
java.io.FileNotFoundException: lib\dotBinaries6\dot.exe (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.processmining.plugins.graphviz.dot.Dot2Image.createDotDirectoryByCopying(Dot2Image.java:183)
	at org.processmining.plugins.graphviz.dot.Dot2Image.getDotDirectory(Dot2Image.java:164)
	at org.processmining.plugins.graphviz.dot.Dot2Image.dot2imageInputStream(Dot2Image.java:37)
	at org.processmining.plugins.graphviz.dot.Dot2Image.dot2imageInputStream(Dot2Image.java:30)
	at org.processmining.plugins.graphviz.visualisation.DotPanel.dot2svg(DotPanel.java:437)
	at org.processmining.plugins.graphviz.visualisation.DotPanel.<init>(DotPanel.java:116)
	at org.processmining.plugins.inductiveVisualMiner.plugins.ProcessTreeVisualisationPlugin.fancy(ProcessTreeVisualisationPlugin.java:25)
	at org.rapidprom.ioobjectrenderers.ProcessTreeIOObjectDotRenderer.runVisualization(ProcessTreeIOObjectDotRenderer.java:19)
	at org.rapidprom.ioobjectrenderers.ProcessTreeIOObjectDotRenderer.runVisualization(ProcessTreeIOObjectDotRenderer.java:9)
	at org.rapidprom.ioobjectrenderers.abstr.AbstractRapidProMIOObjectRenderer.getVisualizationComponent(AbstractRapidProMIOObjectRenderer.java:23)
	at com.rapidminer.gui.processeditor.results.ResultDisplayTools$1.run(ResultDisplayTools.java:168)
	at com.rapidminer.gui.tools.ProgressThread$3.run(ProgressThread.java:550)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Stack trace:

  org.processmining.plugins.graphviz.dot.Dot2Image.dot2imageInputStream(Dot2Image.java:40)
  org.processmining.plugins.graphviz.dot.Dot2Image.dot2imageInputStream(Dot2Image.java:30)
  org.processmining.plugins.graphviz.visualisation.DotPanel.dot2svg(DotPanel.java:437)
  org.processmining.plugins.graphviz.visualisation.DotPanel.<init>(DotPanel.java:116)
  org.processmining.plugins.inductiveVisualMiner.plugins.ProcessTreeVisualisationPlugin.fancy(ProcessTreeVisualisationPlugin.java:25)
  org.rapidprom.ioobjectrenderers.ProcessTreeIOObjectDotRenderer.runVisualization(ProcessTreeIOObjectDotRenderer.java:19)
  org.rapidprom.ioobjectrenderers.ProcessTreeIOObjectDotRenderer.runVisualization(ProcessTreeIOObjectDotRenderer.java:9)
  org.rapidprom.ioobjectrenderers.abstr.AbstractRapidProMIOObjectRenderer.getVisualizationComponent(AbstractRapidProMIOObjectRenderer.java:23)
  com.rapidminer.gui.processeditor.results.ResultDisplayTools$1.run(ResultDisplayTools.java:168)
  com.rapidminer.gui.tools.ProgressThread$3.run(ProgressThread.java:550)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)

**Comment by s-j-v-zelst** [comment]
this is due to a (recent) fix, that kind of breaks graphviz in rapidprom.
Sander will fix this.

**Comment by s-j-v-zelst** [comment]
I have added GraphViz 6.7.183 to the libraries repository (9d78c394e101ed490f47f97448bb3ce09f89df15)
I have updated the integration branch accordingly (1a281bd421d77450ecd7d959d86312eb444ace93).
@abolt can you test this? (try to run it without any .ProM folder in the user home).
Don't forget to refresh the caches.

**Comment by abolt** [comment]
It does not work. I get the same error:


dot directory lib\dotBinaries6 does not exist; create it and copy binaries to it
copy dot.exe
java.io.FileNotFoundException: lib\dotBinaries6\dot.exe (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.processmining.plugins.graphviz.dot.Dot2Image.createDotDirectoryByCopying(Dot2Image.java:191)
	at org.processmining.plugins.graphviz.dot.Dot2Image.getDotDirectory(Dot2Image.java:172)
	at org.processmining.plugins.graphviz.dot.Dot2Image.dot2imageInputStream(Dot2Image.java:37)
	at org.processmining.plugins.graphviz.dot.Dot2Image.dot2imageInputStream(Dot2Image.java:30)
	at org.processmining.plugins.graphviz.visualisation.DotPanel.dot2svg(DotPanel.java:437)
	at org.processmining.plugins.graphviz.visualisation.DotPanel.<init>(DotPanel.java:116)
	at org.processmining.plugins.inductiveVisualMiner.plugins.ProcessTreeVisualisationPlugin.fancy(ProcessTreeVisualisationPlugin.java:25)
	at org.rapidprom.ioobjectrenderers.ProcessTreeIOObjectDotRenderer.runVisualization(ProcessTreeIOObjectDotRenderer.java:19)
	at org.rapidprom.ioobjectrenderers.ProcessTreeIOObjectDotRenderer.runVisualization(ProcessTreeIOObjectDotRenderer.java:9)
	at org.rapidprom.ioobjectrenderers.abstr.AbstractRapidProMIOObjectRenderer.getVisualizationComponent(AbstractRapidProMIOObjectRenderer.java:23)
	at com.rapidminer.gui.processeditor.results.ResultDisplayTools$1.run(ResultDisplayTools.java:168)
	at com.rapidminer.gui.tools.ProgressThread$3.run(ProgressThread.java:550)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by abolt** [comment]
now it works
