### ISSUE TITLE
Log Dialog visualization works but causes exception

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#23]
Scenario: visualize an XLog object (e.g. import XLog and provide as output).

Although the LogDialog is shown, an exception is produced:

`Exception in thread "AWT-EventQueue-0" java.awt.IllegalComponentStateException: component must be showing on the screen to determine
 its location
        at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2054)
        at java.awt.Component.getLocationOnScreen(Component.java:2028)
        at org.processmining.framework.util.ui.widgets.InspectorPanel.resize(InspectorPanel.java:155)
        at org.processmining.framework.util.ui.widgets.InspectorPanel$2.componentResized(InspectorPanel.java:87)
        at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
        at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
        at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
        at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
        at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
        at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
        at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
        at java.awt.Component.processComponentEvent(Component.java:6351)
        at java.awt.Component.processEvent(Component.java:6305)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by abolt** [comment]
Could you probide me with the log that gave you that exception? In tested this with 5 different logs and I do not get that exception

**Comment by fmannhardt** [comment]
I encountered the same problem. any log will do. The exception is not shown in RapidMiner but just on the console. I think it has to do with the LogProjection plugin, as this one uses an Inspector, which is shown outside of the RapidProM window.
