### ISSUE TITLE
ClassNotFound for several Operators

### ISSUE THREAD

**Issue by fmannhardt** [rapidprom/rapidprom-source#54]
I get the following ClassNotFoundExceptions for the current integration branch. Mostly related to Niek's code. So probably some packages needs updating.

> WARNING: Cannot create operator description: rmx_rapidprom : ne_precision
> java.lang.ClassNotFoundException: org.rapidprom.operators.conformance.NEPrecisionOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : entopy_projections_greedy
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.GreedyEntropyBasedLogFilterOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : entopy_projections_direct
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.DirectEntropyBasedLogFilterOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : entopy_projections_direct2
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.DirectEntropyBasedLogFilterOperator2
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : entopy_projections_beam
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.BeamEntropyBasedLogFilterOperator3
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : entopy_projections_greedy3
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.GreedyEntropyBasedLogFilterOperator3
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : entopy_projections_greedy2
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.GreedyEntropyBasedLogFilterOperator2
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : entopy_projections_global
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.EntropyBasedLogFilterOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : kl_projections_greedy
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.GreedyKLBasedLogFilterOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : frequency_projections_1
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.FrequencyBasedLogFilter1Operator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : frequency_projections_2
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.FrequencyBasedLogFilter2Operator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : random_projections
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.RandomLogFilterOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : entropy_adjusted_projections
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.GreedyAdjustedEntropyBasedLogFilterOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : apply_log_projection
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.ApplyProjectionOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : calculate_determinism
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.DeterminismCalculatorOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : contain_only_complete_log
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.OnlyContainCompleteEventsOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)
> 
> Aug 09, 2017 1:55:23 PM com.rapidminer.tools.OperatorService parseOperators
> WARNING: Cannot create operator description: rmx_rapidprom : rprom_clear_threads
> java.lang.ClassNotFoundException: org.rapidprom.operators.niek.RapidProMThreadCleanUpOperator
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at com.rapidminer.tools.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:131)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.rapidminer.operator.OperatorDescription.<init>(OperatorDescription.java:137)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:354)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:346)
> 	at com.rapidminer.tools.OperatorService.parseOperators(OperatorService.java:320)
> 	at com.rapidminer.tools.OperatorService.registerOperators(OperatorService.java:267)
> 	at com.rapidminer.tools.plugin.Plugin.registerOperators(Plugin.java:633)
> 	at com.rapidminer.tools.plugin.Plugin.registerAllPluginOperators(Plugin.java:1034)
> 	at com.rapidminer.tools.OperatorService.init(OperatorService.java:174)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:694)
> 	at com.rapidminer.RapidMiner.init(RapidMiner.java:619)
> 	at com.rapidminer.gui.RapidMinerGUI.run(RapidMinerGUI.java:336)
> 	at com.rapidminer.gui.RapidMinerGUI.launch(RapidMinerGUI.java:816)
> 	at com.rapidminer.gui.RapidMinerGUI.main(RapidMinerGUI.java:792)
> 	at com.rapidminer.GuiLauncher.main(GuiLauncher.java:13)

**Comment by s-j-v-zelst** [comment]
I have removed some of these operators indeed, I haven't updated the operator descriptions yet.
Will do it in a later phase.

**Comment by s-j-v-zelst** [comment]
Some of them need to be incorporated, in a different package though...
